cliente: "TEST COMPANY"
id_contrato: "9931"
tipo_documento: "PRODUCTO"
codigo_almacen: "ALM01"

salida:
  columnas:
    - Cliente
    - ID Contrato
    - Tipo
    - Cod. Almacén
    - Nº Ref. Cruzada
    - Código Navision
    - Descripción
    - Cantidad
    - Precio Unitario
    - Divisa
    - Fecha Entrega
